server:
  port: ${PORT:8000}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shikong
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    database: 1
    password: redisxiao
    port: 6379
    timeout: 5000
    pool:
      min-idle: 1
      max-wait: 2
      max-idle: 5
mybatis:
  mapper-locations:
    - com/shikong/user/mapper/*.xml
    
  