server:
  port: ${PORT:8000}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shikong
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations:
    - com.shikong.user.mapper.UserMapper.xml